#!/usr/bin/env node
/**
 * ClawRouter CLI
 *
 * Standalone proxy for deployed setups where the proxy needs to survive gateway restarts.
 *
 * Usage:
 *   npx @blockrun/clawrouter              # Start standalone proxy
 *   npx @blockrun/clawrouter --version    # Show version
 *   npx @blockrun/clawrouter --port 8402  # Custom port
 *
 * For production deployments, use with PM2:
 *   pm2 start "npx @blockrun/clawrouter" --name clawrouter
 */

import { startProxy, getProxyPort } from "./proxy.js";
import { VERSION } from "./version.js";
import {
  resolveOrGenerateWalletKey,
  resolvePaymentChain,
  recoverWalletFromMnemonic,
  savePaymentChain,
} from "./auth.js";
import { getSolanaAddress } from "./wallet.js";
import { generateReport } from "./report.js";
import { formatRecentLogs } from "./stats.js";
import { runDoctor } from "./doctor.js";
import { PARTNER_SERVICES } from "./partners/index.js";
import { runPolicyCommand } from "./commands/policy.js";
import {
  clearApiKey,
  isValidApiKey,
  maskApiKey,
  resolveApiKey,
  saveApiKey,
  PORTAL_KEYS_URL,
  PORTAL_CREDITS_URL,
  PORTAL_URL,
} from "./api-key.js";

function printHelp(): void {
  console.log(`
ClawRouter v${VERSION} - Smart LLM Router

Usage:
  clawrouter [options]
  clawrouter login [brk_...]           # Use a BlockRun API key (card-funded credit)
  clawrouter logout                    # Forget the API key and go back to the wallet
  clawrouter status                    # Live proxy status (wallet, balance, chain)
  clawrouter wallet                    # Wallet details + balance
  clawrouter models                    # List available models
  clawrouter stats [--days <n>]        # Usage stats (default: 7 days)
  clawrouter doctor [opus] [question]
  clawrouter partners [test]
  clawrouter report [daily|weekly|monthly] [--json]
  clawrouter logs [--days <n>]
  clawrouter setup                     # Finish OpenClaw integration after npm install -g
  clawrouter policy                    # Spend limits + payee/network/asset lists on disk
  clawrouter policy set|add|remove <list> <value>...
  clawrouter policy clear <list>       # <list>: allowedPayees|blockedPayees|allowedNetworks|allowedAssets
  clawrouter policy limit <window> <usd>|clear   # <window>: perRequest|hourly|daily|session
  clawrouter share last [--as=<im>]    # Convert most recent response for IM (default: feishu)
  clawrouter share list [--limit=<n>]  # Recent response ids + summaries
  clawrouter share <id> [--as=<im>]    # Convert a specific response by id
  clawrouter share last --all          # Write all 6 IM variants to /tmp/
                                       # IM presets: feishu, slack, discord, telegram, whatsapp, plain
  clawrouter phone numbers list                  # List wallet's active phone numbers + expiry
  clawrouter phone numbers buy <US|CA> [--area-code <code>]   # Buy 30-day number lease ($5)
  clawrouter phone numbers renew <+E.164>        # Extend lease 30 days ($5)
  clawrouter phone numbers release <+E.164>      # Release a wallet-owned number (free)
  clawrouter phone lookup <+E.164>               # Carrier + line type ($0.01)
  clawrouter phone fraud <+E.164>                # SIM-swap + forwarding fraud signals ($0.05)

Options:
  --version, -v     Show version number
  --help, -h        Show this help message
  --port <number>   Port to listen on (default: ${getProxyPort()})
  --no-reuse        Refuse an existing listener (used by managed Desktop startup)

Query Commands (talk to running proxy on localhost:${getProxyPort()}):
  status            Proxy status: wallet, balance, payment chain
  wallet            Wallet addresses + USDC balance
  models            List all available models with pricing
  stats             Usage breakdown: requests, cost, top models
  stats --days 14   Custom time range (max 30 days)
  cache             Response cache stats (hit rate, size)

Management Commands:
  setup             Finish OpenClaw integration (run after npm install -g).
                    Registers ClawRouter as a plugin, syncs the model allowlist,
                    and writes the auth profile. Idempotent — safe to re-run.
  doctor            AI-powered diagnostics (default: Sonnet ~$0.003)
  doctor opus       Use Opus for deeper analysis (~$0.01)
  logs              Per-request breakdown: model, cost, latency, status
  logs --days 7     Show last 7 days of requests (default: 1 day)
  partners          List available partner APIs with pricing
  partners test     Test partner API endpoints (expect 402 = alive)
  wallet recover    Restore wallet.key from mnemonic (if generated by ClawRouter)
  login             Store a BlockRun API key in ~/.blockrun/.api-key (persists)
  logout            Delete the stored API key and fall back to the wallet
  chain solana      Switch to Solana (persists)
  chain base        Switch to Base EVM (persists)
  policy            Edit spend limits and counterparty lists (fail-closed; restart proxy to apply)

Paying for calls — two ways, and ClawRouter prefers the API key when both exist:
  API key   Sign up at ${PORTAL_URL}, top up with a card, mint a key, then run
            "clawrouter login brk_live_...". Calls go to api.blockrun.ai.
  Wallet    The default. A USDC wallet is generated on first run and pays for
            each call over x402 — Solana for new installs, Base for older ones.

Environment Variables:
  BLOCKRUN_API_KEY        BlockRun API key (brk_...) — wins over the wallet when set
  BLOCKRUN_WALLET_KEY     Private key for x402 payments (auto-generated if not set)
  BLOCKRUN_PROXY_PORT     Default proxy port (default: 8402)
  TWZRD_AUTO_GATE         Set to 1 to compose TWZRD AutoGate after SpendControl (default off)

For more info: https://blockrun.ai/clawrouter.md
`);
}

/** Query the running proxy HTTP API */
async function queryProxy(path: string, port: number): Promise<unknown> {
  const res = await fetch(`http://127.0.0.1:${port}${path}`);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  return res.json();
}

/**
 * Pipe text into the system clipboard via the platform-native command.
 * Returns null on success, or a short message describing why it failed.
 * Never throws — clipboard is best-effort.
 */
async function copyToClipboard(text: string): Promise<string | null> {
  const { spawn } = await import("node:child_process");
  const platform = process.platform;
  const candidates: Array<[string, string[]]> =
    platform === "darwin"
      ? [["pbcopy", []]]
      : platform === "win32"
        ? [["clip", []]]
        : [
            ["wl-copy", []],
            ["xclip", ["-selection", "clipboard"]],
            ["xsel", ["--clipboard", "--input"]],
          ];
  for (const [cmd, args] of candidates) {
    try {
      const child = spawn(cmd, args, { stdio: ["pipe", "ignore", "ignore"] });
      const ok = await new Promise<boolean>((resolve) => {
        let settled = false;
        child.on("error", () => {
          if (!settled) {
            settled = true;
            resolve(false);
          }
        });
        child.on("close", (code) => {
          if (!settled) {
            settled = true;
            resolve(code === 0);
          }
        });
        child.stdin.end(text, "utf8");
      });
      if (ok) return null;
    } catch {
      // try next candidate
    }
  }
  return platform === "darwin"
    ? "pbcopy not available"
    : platform === "win32"
      ? "clip.exe not available"
      : "no clipboard tool found (install xclip, xsel, or wl-clipboard)";
}

interface ShareEntry {
  id: string;
  timestamp: string;
  model?: string;
  sessionId?: string;
  requestSummary: string;
  responseLength?: number;
  responseText?: string;
}

interface ShareRendered {
  id: string;
  timestamp: string;
  model?: string;
  preset: string;
  rendered: string;
}

const VALID_PRESETS = ["feishu", "slack", "discord", "telegram", "whatsapp", "plain"];

async function cmdShare(
  port: number,
  target: string | undefined,
  preset: string | undefined,
  limit: number,
  all: boolean,
): Promise<void> {
  // Default target = "last" if user just typed `clawrouter share`.
  const tgt = target ?? "last";

  if (tgt === "list") {
    try {
      const entries = (await queryProxy(`/share/list?limit=${limit}`, port)) as ShareEntry[];
      if (entries.length === 0) {
        console.log("\nNo responses persisted yet.");
        console.log(
          "  Send a request through ClawRouter and try again, or check BLOCKRUN_RESPONSE_STORE.\n",
        );
        return;
      }
      console.log(`\nRecent responses (${entries.length}):\n`);
      for (const e of entries) {
        const t = new Date(e.timestamp).toLocaleString();
        const summary = e.requestSummary || "(no prompt)";
        const len = e.responseLength ? ` ${e.responseLength}b` : "";
        console.log(`  ${e.id}  ${t}  [${e.model ?? "?"}${len}]`);
        console.log(`    ${summary}`);
      }
      console.log(
        `\nUse: clawrouter share <id> --as=<feishu|slack|discord|telegram|whatsapp|plain>\n`,
      );
    } catch (err) {
      console.error(`✗ Cannot fetch share list: ${err instanceof Error ? err.message : err}`);
      console.error(`  Is the proxy running on port ${port}?`);
      process.exit(1);
    }
    return;
  }

  // Render path: target is "last" or a specific id.
  const idOrLast = tgt === "last" ? "last" : tgt;

  // --all: render every preset to /tmp/, print the paths.
  if (all) {
    try {
      const { writeFile } = await import("node:fs/promises");
      const { tmpdir } = await import("node:os");
      const { join: pjoin } = await import("node:path");
      const paths: string[] = [];
      for (const p of VALID_PRESETS) {
        const path =
          idOrLast === "last" ? `/share/last?as=${p}` : `/share/${idOrLast}/render?as=${p}`;
        const result = (await queryProxy(path, port)) as ShareRendered;
        const file = pjoin(tmpdir(), `claw-share-${result.id}-${p}.txt`);
        await writeFile(file, result.rendered, "utf8");
        paths.push(file);
      }
      console.log("\n✓ Wrote all 6 preset variants:");
      for (const p of paths) console.log(`  ${p}`);
      console.log();
    } catch (err) {
      console.error(`✗ Failed: ${err instanceof Error ? err.message : err}`);
      process.exit(1);
    }
    return;
  }

  const chosenPreset = preset ?? process.env.BLOCKRUN_DEFAULT_SHARE_PRESET ?? "feishu";
  if (!VALID_PRESETS.includes(chosenPreset)) {
    console.error(`✗ Unknown preset: ${chosenPreset}`);
    console.error(`  Valid: ${VALID_PRESETS.join(", ")}`);
    process.exit(1);
  }

  try {
    const path =
      idOrLast === "last"
        ? `/share/last?as=${chosenPreset}`
        : `/share/${idOrLast}/render?as=${chosenPreset}`;
    const result = (await queryProxy(path, port)) as ShareRendered;
    process.stdout.write(result.rendered);
    if (!result.rendered.endsWith("\n")) process.stdout.write("\n");
    const clipErr = await copyToClipboard(result.rendered);
    const sizeKb = (result.rendered.length / 1024).toFixed(1);
    if (clipErr) {
      console.error(`\n(clipboard skipped: ${clipErr})`);
    } else {
      console.error(`\n✓ Copied to clipboard (preset=${chosenPreset}, ${sizeKb}KB)`);
    }
  } catch (err) {
    console.error(`✗ Cannot fetch share: ${err instanceof Error ? err.message : err}`);
    console.error(`  Is the proxy running on port ${port}?`);
    process.exit(1);
  }
}

/**
 * Diff the local usage journal against BlockRun's billing ledger.
 *
 * API-key only: the ledger is per account, and a wallet's spend is on-chain
 * rather than in an account ledger, so there is nothing to reconcile against.
 * Needs no running proxy — it reads the journal on disk and the gateway.
 */
async function cmdReconcile(days: number): Promise<void> {
  const resolved = await resolveApiKey().catch((error: unknown) => {
    console.error(`✗ ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  });
  if (!resolved) {
    console.error(`✗ Reconciliation needs a BlockRun API key — it compares against your account`);
    console.error(`  ledger. Wallet spend settles on-chain instead; see "clawrouter stats".`);
    console.error(`  Sign in at ${PORTAL_URL} and run: clawrouter login brk_live_...`);
    process.exit(1);
  }
  try {
    const { reconcile, formatReconcile } = await import("./reconcile.js");
    const result = await reconcile(resolved.key, days);
    console.log(formatReconcile(result, days));
    // Money charged that this machine cannot account for is the one outcome
    // worth a non-zero exit, so a scheduled check can alert on it.
    process.exitCode = result.chargedNotRecorded.length > 0 ? 2 : 0;
  } catch (error) {
    console.error(`✗ ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}

async function cmdStatus(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/health?full=true", port)) as Record<string, unknown>;
    console.log(`\nClawRouter Status (port ${port})\n`);
    console.log(`  Status:        ${data.status}`);
    if (data.authMode === "api-key") {
      console.log(`  Auth:          BlockRun API key ${data.apiKey}`);
      console.log(`  Gateway:       ${data.gateway}`);
      console.log(`  Billing:       account credit — top up at ${PORTAL_CREDITS_URL}`);
      if (data.creditSummary) console.log(`  Credit:        ${data.creditSummary}`);
      if (data.blocked) {
        console.log(`  ⚠ Account is blocked${data.blockedReason ? `: ${data.blockedReason}` : ""}`);
      } else if (data.isEmpty) {
        console.log(`  ⚠ Credit exhausted — top up at ${PORTAL_CREDITS_URL}`);
      }
    } else {
      console.log(`  Auth:          wallet (x402)`);
      console.log(`  Payment Chain: ${data.paymentChain}`);
      console.log(`  EVM Wallet:    ${data.wallet}`);
      if (data.solana) console.log(`  Solana Wallet: ${data.solana}`);
      console.log(`  Balance:       ${data.balance ?? "unknown"}`);
      if (data.isLow) console.log(`  ⚠ Balance is low`);
      if (data.isEmpty) console.log(`  ⚠ Balance is empty — using free models`);
    }
    if (data.upstreamProxy) console.log(`  Upstream Proxy: ${data.upstreamProxy}`);
    console.log();
  } catch {
    console.error(`✗ Cannot connect to ClawRouter on port ${port}`);
    console.error(`  Is the proxy running? Start with: npx @blockrun/clawrouter`);
    process.exit(1);
  }
}

async function cmdWallet(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/health?full=true", port)) as Record<string, unknown>;
    if (data.authMode === "api-key") {
      // There is no wallet in this mode. Say so plainly rather than printing an
      // empty address table that reads like a broken install.
      console.log(`\nClawRouter Account\n`);
      console.log(`  Auth:    BlockRun API key ${data.apiKey}`);
      console.log(`  Gateway: ${data.gateway}`);
      console.log(`  Billing: account credit (no wallet, no chain)`);
      if (data.creditSummary) console.log(`  Credit:  ${data.creditSummary}`);
      console.log(`  Top up:  ${PORTAL_CREDITS_URL}`);
      console.log(`  Usage:   ${PORTAL_URL}/dashboard`);
      console.log();
      console.log(`  To pay with a USDC wallet instead: clawrouter logout`);
      console.log();
      return;
    }
    console.log(`\nClawRouter Wallet\n`);
    console.log(`  Payment Chain: ${data.paymentChain}`);
    console.log();
    console.log(`  Base (EVM):`);
    console.log(`    Address: ${data.wallet}`);
    console.log(`    Fund:    https://basescan.org/address/${data.wallet}`);
    if (data.solana) {
      console.log();
      console.log(`  Solana:`);
      console.log(`    Address: ${data.solana}`);
      console.log(`    Fund:    https://solscan.io/account/${data.solana}`);
    }
    console.log();
    console.log(`  Balance: ${data.balance ?? "unknown"} (USDC)`);
    if (data.isEmpty) console.log(`  ⚠ Empty — fund wallet or use free models`);
    console.log();
  } catch {
    console.error(`✗ Cannot connect to ClawRouter on port ${port}`);
    process.exit(1);
  }
}

async function cmdModels(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/v1/models", port)) as {
      data: Array<{ id: string; owned_by?: string }>;
    };
    console.log(`\nAvailable Models (${data.data.length})\n`);

    // Group by provider
    const groups = new Map<string, string[]>();
    for (const m of data.data) {
      const provider = m.id.includes("/") ? m.id.split("/")[0] : "blockrun";
      if (!groups.has(provider)) groups.set(provider, []);
      groups.get(provider)!.push(m.id);
    }

    for (const [provider, models] of groups) {
      console.log(`  ${provider} (${models.length}):`);
      for (const id of models) {
        console.log(`    ${id}`);
      }
      console.log();
    }
  } catch {
    console.error(`✗ Cannot connect to ClawRouter on port ${port}`);
    process.exit(1);
  }
}

async function cmdStats(port: number, days: number): Promise<void> {
  try {
    const data = (await queryProxy(`/stats?days=${days}`, port)) as Record<string, unknown>;
    const stats = data as {
      totalRequests?: number;
      totalCostUsd?: number;
      savedUsd?: number;
      savingsPercent?: number;
      topModels?: Array<{ model: string; requests: number; costUsd: number }>;
    };

    console.log(`\nUsage Stats (last ${days} days)\n`);
    console.log(`  Requests: ${stats.totalRequests ?? 0}`);
    console.log(`  Cost:     $${(stats.totalCostUsd ?? 0).toFixed(4)}`);
    if (stats.savedUsd) {
      console.log(
        `  Saved:    $${stats.savedUsd.toFixed(4)} (${stats.savingsPercent?.toFixed(0) ?? 0}% vs Opus)`,
      );
    }

    if (stats.topModels && stats.topModels.length > 0) {
      console.log();
      console.log(`  Top Models:`);
      for (const m of stats.topModels.slice(0, 10)) {
        console.log(
          `    ${m.model.padEnd(40)} ${String(m.requests).padStart(5)} reqs  $${m.costUsd.toFixed(4)}`,
        );
      }
    }
    console.log();
  } catch {
    console.error(`✗ Cannot connect to ClawRouter on port ${port}`);
    process.exit(1);
  }
}

/**
 * `clawrouter phone ...` — wallet-facing phone CLI.
 *
 * All operations POST to the local proxy at `/v1/phone/...` (or `/v1/voice/...`),
 * which transparently handles x402 payment via the wallet. The CLI just renders
 * upstream JSON in a human format.
 */
async function cmdPhone(
  port: number,
  subcommand: "numbers" | "lookup" | "fraud",
  numbersAction: "list" | "buy" | "renew" | "release" | undefined,
  arg: string | undefined,
  areaCode: string | undefined,
): Promise<void> {
  const base = `http://127.0.0.1:${port}`;

  async function postJson(path: string, body: unknown): Promise<unknown> {
    const resp = await fetch(`${base}${path}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body),
    });
    const text = await resp.text();
    if (!resp.ok) {
      if (resp.status === 402) {
        throw new Error(
          `Insufficient wallet balance (HTTP 402). Fund wallet via clawrouter wallet.\n${text}`,
        );
      }
      throw new Error(`HTTP ${resp.status}: ${text}`);
    }
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }

  function fmtExpiry(expiresAt: string): string {
    const ms = new Date(expiresAt).getTime();
    if (!Number.isFinite(ms)) return expiresAt;
    const days = Math.round((ms - Date.now()) / (1000 * 60 * 60 * 24));
    const dateStr = new Date(ms).toISOString().split("T")[0];
    if (days < 0) return `${dateStr} (expired ${-days}d ago)`;
    if (days <= 2) return `${dateStr} (in ${days}d) ⚠ renew soon`;
    return `${dateStr} (in ${days}d)`;
  }

  try {
    if (subcommand === "numbers") {
      if (!numbersAction || numbersAction === "list") {
        const result = (await postJson("/v1/phone/numbers/list", {})) as {
          numbers?: Array<{ phone_number: string; expires_at: string; country?: string }>;
        };
        const numbers = result.numbers ?? [];
        if (numbers.length === 0) {
          console.log("\nNo phone numbers owned by this wallet.\n");
          console.log("Buy one with: clawrouter phone numbers buy US [--area-code 415]\n");
          return;
        }
        console.log(`\nActive numbers (${numbers.length}):\n`);
        const numWidth = Math.max(...numbers.map((n) => n.phone_number.length), 16);
        for (const n of numbers) {
          const country = (n.country ?? "??").padEnd(3);
          console.log(
            `  ${n.phone_number.padEnd(numWidth)}  ${country}  expires ${fmtExpiry(n.expires_at)}`,
          );
        }
        console.log();
      } else if (numbersAction === "buy") {
        const country = (arg ?? "").toUpperCase();
        if (country !== "US" && country !== "CA") {
          console.error("✗ Country must be 'US' or 'CA'");
          console.error("  Usage: clawrouter phone numbers buy <US|CA> [--area-code <code>]");
          process.exit(1);
        }
        const body: Record<string, string> = { country };
        if (areaCode) body.areaCode = areaCode;
        console.log(
          `\nBuying ${country} number${areaCode ? ` (area code ${areaCode})` : ""}... ($5.00 / 30-day lease)\n`,
        );
        const result = (await postJson("/v1/phone/numbers/buy", body)) as {
          phone_number?: string;
          expires_at?: string;
        };
        if (result.phone_number) {
          console.log(`  ✓ ${result.phone_number}`);
          if (result.expires_at) console.log(`    expires ${fmtExpiry(result.expires_at)}`);
          console.log();
        } else {
          console.log(JSON.stringify(result, null, 2));
        }
      } else if (numbersAction === "renew") {
        if (!arg) {
          console.error("✗ Usage: clawrouter phone numbers renew <+E.164-number>");
          process.exit(1);
        }
        console.log(`\nRenewing ${arg}... ($5.00 / +30 days)\n`);
        const result = (await postJson("/v1/phone/numbers/renew", { phoneNumber: arg })) as {
          phone_number?: string;
          expires_at?: string;
        };
        console.log(`  ✓ ${result.phone_number ?? arg}`);
        if (result.expires_at) console.log(`    expires ${fmtExpiry(result.expires_at)}`);
        console.log();
      } else if (numbersAction === "release") {
        if (!arg) {
          console.error("✗ Usage: clawrouter phone numbers release <+E.164-number>");
          process.exit(1);
        }
        console.log(`\nReleasing ${arg}...\n`);
        await postJson("/v1/phone/numbers/release", { phoneNumber: arg });
        console.log(`  ✓ Released ${arg}\n`);
      }
    } else if (subcommand === "lookup" || subcommand === "fraud") {
      if (!arg) {
        console.error(`✗ Usage: clawrouter phone ${subcommand} <+E.164-number>`);
        process.exit(1);
      }
      const path = subcommand === "fraud" ? "/v1/phone/lookup/fraud" : "/v1/phone/lookup";
      const price = subcommand === "fraud" ? "$0.05" : "$0.01";
      console.log(`\nLooking up ${arg}... (${price})\n`);
      const result = await postJson(path, { phoneNumber: arg });
      console.log(JSON.stringify(result, null, 2));
      console.log();
    }
  } catch (err) {
    console.error(`✗ ${err instanceof Error ? err.message : String(err)}`);
    console.error(`  Is the proxy running on port ${port}? (start: npx @blockrun/clawrouter)`);
    process.exit(1);
  }
}

async function cmdCache(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/cache", port)) as Record<string, unknown>;
    console.log(`\nCache Stats\n`);
    for (const [key, value] of Object.entries(data)) {
      console.log(`  ${key}: ${JSON.stringify(value)}`);
    }
    console.log();
  } catch {
    console.error(`✗ Cannot connect to ClawRouter on port ${port}`);
    process.exit(1);
  }
}

/**
 * `clawrouter setup` — finish OpenClaw integration after `npm install -g`.
 *
 * Bare `npm install -g @blockrun/clawrouter` puts the package on disk and
 * adds the `clawrouter` binary to PATH, but performs ZERO OpenClaw plugin
 * registration: no entry in openclaw.json's `plugins.entries`, no provider
 * registration, no models allowlist sync, no auth profile. The bot ends up
 * showing OpenClaw's hardcoded default models (~7 entries) and the user
 * thinks ClawRouter "doesn't work".
 *
 * This command repairs that by running the steps OpenClaw's plugin lifecycle
 * would have run: `openclaw plugins install --force` (registration), then
 * directly invoking `injectModelsConfig` and `injectAuthProfile` with
 * `forceWrite: true` to bypass the install-transaction guard added in
 * v0.12.184. Result: the user's openclaw.json now has the full ~44-entry
 * blockrun model allowlist and the `blockrun:default` auth profile.
 *
 * Idempotent — safe to run repeatedly. Use this after `npm install -g` to
 * complete setup, or after a stuck partial install to repair config.
 */
async function cmdSetup(): Promise<void> {
  const { execFileSync, execSync } = await import("node:child_process");
  const {
    copyFileSync,
    cpSync,
    existsSync,
    mkdirSync,
    readFileSync,
    readdirSync,
    renameSync,
    rmSync,
    unlinkSync,
    writeFileSync,
  } = await import("node:fs");
  const { dirname, join } = await import("node:path");
  const { homedir } = await import("node:os");
  const { injectModelsConfig, injectAuthProfile, syncAgentModelCache, VISIBLE_OPENCLAW_MODELS } =
    await import("./index.js");
  const { BLOCKRUN_PLUGIN_ID, prepareBlockRunPluginConfig } =
    await import("./openclaw-plugin-config.js");

  console.log("🦞 ClawRouter setup\n");

  // Step 1: locate OpenClaw. `command -v` alone is not enough — npm runs lifecycle
  // scripts with a stripped PATH, so a perfectly working global install can be
  // invisible here and setup would tell the user to install what they already have.
  // Fall back to the standard global-bin locations. (Thanks @0xCheetah1, #206.)
  const openclawPath = ((): string => {
    const candidates: string[] = [];

    try {
      const onPath = execSync("command -v openclaw", {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      if (onPath) candidates.push(onPath);
    } catch {
      // Not on PATH — expected under npm lifecycle scripts.
    }

    if (process.env.npm_config_prefix) {
      candidates.push(join(process.env.npm_config_prefix, "bin", "openclaw"));
    }

    try {
      const npmRoot = execSync("npm root -g", {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      // npm root -g is <prefix>/lib/node_modules → the bin dir is <prefix>/bin
      if (npmRoot) candidates.push(join(dirname(dirname(npmRoot)), "bin", "openclaw"));
    } catch {
      // npm may be unavailable in embedded runtimes.
    }

    candidates.push(
      join(homedir(), ".npm-global", "bin", "openclaw"),
      join(homedir(), ".local", "bin", "openclaw"),
      "/usr/local/bin/openclaw",
    );

    return candidates.find((candidate) => existsSync(candidate)) ?? "";
  })();

  if (!openclawPath) {
    console.error("  ✗ openclaw not found on PATH");
    console.error("    Install OpenClaw first: npm install -g openclaw");
    console.error("    Then re-run: clawrouter setup");
    process.exit(1);
  }
  console.log(`  ✓ Found openclaw at ${openclawPath}`);

  // Step 2: preflight config compatibility before installation. Do not add the
  // renamed id yet: OpenClaw warns about allow/entry ids that are not installed.
  // Never remove `clawrouter`: OpenClaw owns that id.
  const configPath = join(homedir(), ".openclaw", "openclaw.json");
  const configInitiallyExisted = existsSync(configPath);
  const configRollbackBackup = configInitiallyExisted
    ? `${configPath}.before-${BLOCKRUN_PLUGIN_ID}.${Date.now()}`
    : undefined;
  if (configRollbackBackup) copyFileSync(configPath, configRollbackBackup);
  const ensureConfigRollbackBackup = (): string | undefined => {
    return configRollbackBackup;
  };
  let installAttempted = false;
  const openclawRoot = join(homedir(), ".openclaw");
  const findManagedBlockRunInstalls = (): string[] => {
    const candidates = [
      join(openclawRoot, "extensions", BLOCKRUN_PLUGIN_ID),
      join(openclawRoot, "extensions", "clawrouter"),
      join(openclawRoot, "npm", "node_modules", "@blockrun", "clawrouter"),
    ];
    const projectsDir = join(openclawRoot, "npm", "projects");
    try {
      for (const project of readdirSync(projectsDir)) {
        candidates.push(join(projectsDir, project, "node_modules", "@blockrun", "clawrouter"));
      }
    } catch {
      // OpenClaw has not created an npm-project store yet.
    }
    return [...new Set(candidates)].filter((candidate) => {
      try {
        const metadata = JSON.parse(readFileSync(join(candidate, "package.json"), "utf8")) as {
          name?: unknown;
        };
        return metadata.name === "@blockrun/clawrouter";
      } catch {
        return false;
      }
    });
  };
  const initialPluginDirs = findManagedBlockRunInstalls();
  const setupRollbackRoot = join(
    openclawRoot,
    "blockrun",
    "setup-rollbacks",
    `${Date.now()}-${process.pid}`,
  );
  const pluginRollbackBackups = new Map<string, string>();
  if (initialPluginDirs.length > 0) {
    mkdirSync(setupRollbackRoot, { recursive: true, mode: 0o700 });
    for (const [index, pluginDir] of initialPluginDirs.entries()) {
      const backup = join(setupRollbackRoot, String(index));
      cpSync(pluginDir, backup, { recursive: true });
      pluginRollbackBackups.set(pluginDir, backup);
    }
  }
  const restoreSetupConfig = (): void => {
    if (configRollbackBackup && existsSync(configRollbackBackup)) {
      copyFileSync(configRollbackBackup, configPath);
      console.error(`  ✓ Restored original OpenClaw config from ${configRollbackBackup}`);
    } else if (!configInitiallyExisted && existsSync(configPath)) {
      rmSync(configPath);
      console.error("  ✓ Removed the partially created OpenClaw config");
    }
  };
  const rollbackSetup = (): void => {
    if (installAttempted) {
      if (initialPluginDirs.length === 0) {
        try {
          execFileSync(openclawPath, ["plugins", "uninstall", "--force", BLOCKRUN_PLUGIN_ID], {
            stdio: "ignore",
            timeout: 30_000,
          });
        } catch {
          // Restoring the original config below still leaves a failed install inactive.
        }
      }
      for (const currentDir of findManagedBlockRunInstalls()) {
        if (!pluginRollbackBackups.has(currentDir)) {
          rmSync(currentDir, { recursive: true, force: true });
        }
      }
      for (const [pluginDir, backup] of pluginRollbackBackups) {
        if (!existsSync(backup)) continue;
        rmSync(pluginDir, { recursive: true, force: true });
        mkdirSync(dirname(pluginDir), { recursive: true });
        cpSync(backup, pluginDir, { recursive: true });
      }
    }
    restoreSetupConfig();
    rmSync(setupRollbackRoot, { recursive: true, force: true });
  };
  let legacyBlockRunInstall = false;
  let stagedLegacyEntry: Record<string, unknown> | undefined;
  if (existsSync(configPath)) {
    try {
      const config = JSON.parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
      const legacyPackagePath = join(
        homedir(),
        ".openclaw",
        "extensions",
        "clawrouter",
        "package.json",
      );
      if (existsSync(legacyPackagePath)) {
        try {
          const legacyPackage = JSON.parse(readFileSync(legacyPackagePath, "utf8")) as {
            name?: unknown;
          };
          legacyBlockRunInstall = legacyPackage.name === "@blockrun/clawrouter";
        } catch {
          // An unreadable directory is not proof that the official id was ours.
        }
      }

      let stripUnsupportedInstalls = false;
      try {
        execFileSync(openclawPath, ["config", "validate"], {
          encoding: "utf8",
          stdio: ["ignore", "pipe", "pipe"],
          timeout: 30_000,
        });
      } catch (error) {
        const output = `${error instanceof Error ? error.message : String(error)} ${
          typeof error === "object" && error && "stdout" in error ? String(error.stdout) : ""
        } ${typeof error === "object" && error && "stderr" in error ? String(error.stderr) : ""}`;
        stripUnsupportedInstalls =
          output.includes("Unrecognized key") && output.includes("installs");
      }

      let configChanged = false;
      if (legacyBlockRunInstall) {
        const stagedConfig = structuredClone(config);
        prepareBlockRunPluginConfig(stagedConfig, { legacyBlockRunInstall: true });
        const stagedPlugins = stagedConfig.plugins as
          { entries?: Record<string, Record<string, unknown>> } | undefined;
        const stagedEntries = stagedPlugins?.entries;
        stagedLegacyEntry = stagedEntries?.[BLOCKRUN_PLUGIN_ID];
        const livePlugins = config.plugins as
          { entries?: Record<string, Record<string, unknown>> } | undefined;
        if (stagedEntries?.clawrouter && livePlugins?.entries?.clawrouter) {
          if (
            JSON.stringify(livePlugins.entries.clawrouter) !==
            JSON.stringify(stagedEntries.clawrouter)
          ) {
            livePlugins.entries.clawrouter = stagedEntries.clawrouter;
            configChanged = true;
          }
        }
      }
      configChanged =
        prepareBlockRunPluginConfig(config, { stripUnsupportedInstalls }) || configChanged;

      if (configChanged) {
        const backupPath = ensureConfigRollbackBackup();
        const tmpPath = `${configPath}.tmp.${process.pid}`;
        writeFileSync(tmpPath, `${JSON.stringify(config, null, 2)}\n`, { mode: 0o600 });
        renameSync(tmpPath, configPath);
        console.log(`  ✓ Prepared OpenClaw 2.0 config (backup: ${backupPath})`);
      }
    } catch (err) {
      rollbackSetup();
      console.error(
        `  ✗ Cannot safely prepare OpenClaw config: ${err instanceof Error ? err.message : String(err)}`,
      );
      process.exit(1);
    }
  }

  // Register with the managed OpenClaw plugin lifecycle. OpenClaw 2.0 requires
  // explicit capability consent for this plugin's declared tools.
  console.log("\n→ Registering ClawRouter with OpenClaw...");
  try {
    let acceptsCapabilities = false;
    try {
      const help = execFileSync(openclawPath, ["plugins", "install", "--help"], {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
        timeout: 15_000,
      });
      acceptsCapabilities = help.includes("--accept-capabilities");
    } catch {
      // Older OpenClaw versions do not need the flag.
    }
    const installSpec = process.env.BLOCKRUN_CLAWROUTER_INSTALL_SPEC ?? "@blockrun/clawrouter";
    const installArgs = ["plugins", "install", "--force"];
    if (acceptsCapabilities) installArgs.push("--accept-capabilities");
    installArgs.push(installSpec);
    installAttempted = true;
    execFileSync(openclawPath, installArgs, {
      stdio: "inherit",
      timeout: 180_000,
    });
  } catch (err) {
    rollbackSetup();
    console.error(
      `  ✗ OpenClaw plugin install failed: ${err instanceof Error ? err.message : String(err)}`,
    );
    console.error(
      "    Configuration was rolled back. Fix the error and run `clawrouter setup` again.",
    );
    process.exit(1);
  }

  // The plugin now exists, so enabling its new id no longer produces stale-id
  // warnings. A configured plugins.allow list is exclusive, which is why this
  // explicit post-install step cannot rely on the plugin activating itself.
  if (existsSync(configPath)) {
    try {
      const config = JSON.parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
      if (stagedLegacyEntry) {
        const plugins = (config.plugins ??= {}) as Record<string, unknown>;
        const entries = (plugins.entries ??= {}) as Record<string, unknown>;
        const current = (entries[BLOCKRUN_PLUGIN_ID] ?? {}) as Record<string, unknown>;
        const stagedConfig = stagedLegacyEntry.config as Record<string, unknown> | undefined;
        const currentConfig = current.config as Record<string, unknown> | undefined;
        entries[BLOCKRUN_PLUGIN_ID] = {
          ...stagedLegacyEntry,
          ...current,
          ...(stagedConfig || currentConfig
            ? { config: { ...stagedConfig, ...currentConfig } }
            : {}),
        };
      }
      const configChanged = prepareBlockRunPluginConfig(config, {
        explicitSetup: true,
        legacyBlockRunInstall,
      });
      if (stagedLegacyEntry || configChanged) {
        const backupPath = ensureConfigRollbackBackup();
        const tmpPath = `${configPath}.tmp.${process.pid}`;
        writeFileSync(tmpPath, `${JSON.stringify(config, null, 2)}\n`, { mode: 0o600 });
        renameSync(tmpPath, configPath);
        console.log(
          `  ✓ Enabled ${BLOCKRUN_PLUGIN_ID}${backupPath ? ` (backup: ${backupPath})` : ""}`,
        );
      }
    } catch (err) {
      rollbackSetup();
      console.error(
        `  ✗ Plugin installed, but its config could not be enabled safely: ${err instanceof Error ? err.message : String(err)}`,
      );
      process.exit(1);
    }
  }

  // Step 3: sync the models allowlist + provider config + auth profile directly.
  // forceWrite: true bypasses the gateway-mode guard added in v0.12.184 since
  // this is an explicit user command, not a plugin-activation hook inside an
  // install transaction.
  console.log("\n→ Syncing models allowlist + auth profile...");
  const setupLogger = {
    info: (msg: string) => console.log(`  ${msg}`),
  };
  try {
    if (existsSync(configPath)) ensureConfigRollbackBackup();
    injectModelsConfig(setupLogger, { forceWrite: true });
    syncAgentModelCache(setupLogger, { forceWrite: true });
    injectAuthProfile(setupLogger);
  } catch (err) {
    rollbackSetup();
    console.error(`  ✗ Config sync failed: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  }

  console.log("\n✓ Setup complete.");
  rmSync(setupRollbackRoot, { recursive: true, force: true });
  if (configRollbackBackup && existsSync(configRollbackBackup)) {
    unlinkSync(configRollbackBackup);
  }
  console.log("\nNext: restart the gateway to load ClawRouter:");
  console.log("  openclaw gateway restart");
  console.log(
    `\nThen verify in your bot: /models — you should see ${VISIBLE_OPENCLAW_MODELS.length} BlockRun models.`,
  );
}

function parseArgs(args: string[]): {
  version: boolean;
  help: boolean;
  doctor: boolean;
  logs: boolean;
  logsDays: number;
  partners: boolean;
  partnersTest: boolean;
  report: boolean;
  reportPeriod: "daily" | "weekly" | "monthly";
  reportJson: boolean;
  walletRecover: boolean;
  chain?: "solana" | "base";
  port?: number;
  noReuse: boolean;
  // Query commands
  queryStatus: boolean;
  queryWallet: boolean;
  queryModels: boolean;
  queryStats: boolean;
  queryStatsDays: number;
  reconcile: boolean;
  reconcileDays: number;
  queryCache: boolean;
  setup: boolean;
  // Share commands
  share: boolean;
  shareTarget?: "last" | "list" | string; // string = an id like resp_...
  sharePreset?: string;
  shareLimit: number;
  shareAll: boolean;
  // Phone commands
  phone: boolean;
  phoneSubcommand?: "numbers" | "lookup" | "fraud";
  phoneNumbersAction?: "list" | "buy" | "renew" | "release";
  phoneArg?: string;
  phoneAreaCode?: string;
  policy: boolean;
  policyArgs: string[];
  login: boolean;
  loginKey?: string;
  logout: boolean;
} {
  const result = {
    version: false,
    help: false,
    doctor: false,
    logs: false,
    logsDays: 1,
    partners: false,
    partnersTest: false,
    report: false,
    reportPeriod: "daily" as "daily" | "weekly" | "monthly",
    reportJson: false,
    walletRecover: false,
    chain: undefined as "solana" | "base" | undefined,
    port: undefined as number | undefined,
    noReuse: false,
    queryStatus: false,
    queryWallet: false,
    queryModels: false,
    queryStats: false,
    queryStatsDays: 7,
    reconcile: false,
    reconcileDays: 7,
    queryCache: false,
    setup: false,
    share: false,
    shareTarget: undefined as "last" | "list" | string | undefined,
    sharePreset: undefined as string | undefined,
    shareLimit: 20,
    shareAll: false,
    phone: false,
    phoneSubcommand: undefined as "numbers" | "lookup" | "fraud" | undefined,
    phoneNumbersAction: undefined as "list" | "buy" | "renew" | "release" | undefined,
    phoneArg: undefined as string | undefined,
    phoneAreaCode: undefined as string | undefined,
    policy: false,
    policyArgs: [] as string[],
    login: false,
    loginKey: undefined as string | undefined,
    logout: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--version" || arg === "-v") {
      result.version = true;
    } else if (arg === "--help" || arg === "-h") {
      result.help = true;
    } else if (arg === "status") {
      result.queryStatus = true;
    } else if (arg === "models") {
      result.queryModels = true;
    } else if (arg === "stats") {
      result.queryStats = true;
      if (args[i + 1] === "--days" && args[i + 2]) {
        result.queryStatsDays = Math.min(parseInt(args[i + 2], 10) || 7, 30);
        i += 2;
      }
    } else if (arg === "reconcile") {
      result.reconcile = true;
      if (args[i + 1] === "--days" && args[i + 2]) {
        result.reconcileDays = Math.min(parseInt(args[i + 2], 10) || 7, 90);
        i += 2;
      }
    } else if (arg === "cache") {
      result.queryCache = true;
    } else if (arg === "doctor" || arg === "--doctor") {
      result.doctor = true;
    } else if (arg === "logs") {
      result.logs = true;
      if (args[i + 1] === "--days" && args[i + 2]) {
        result.logsDays = parseInt(args[i + 2], 10) || 1;
        i += 2;
      }
    } else if (arg === "partners") {
      result.partners = true;
      if (args[i + 1] === "test") {
        result.partnersTest = true;
        i++;
      }
    } else if (arg === "report") {
      result.report = true;
      const next = args[i + 1];
      if (next && ["daily", "weekly", "monthly"].includes(next)) {
        result.reportPeriod = next as "daily" | "weekly" | "monthly";
        i++;
        if (args[i + 1] === "--json") {
          result.reportJson = true;
          i++;
        }
      } else if (next === "--json") {
        result.reportJson = true;
        i++;
      }
    } else if (arg === "wallet") {
      if (args[i + 1] === "recover") {
        result.walletRecover = true;
        i++;
      } else if (args[i + 1] === "solana" || args[i + 1] === "base") {
        result.chain = args[i + 1] as "solana" | "base";
        i++;
      } else {
        result.queryWallet = true;
      }
    } else if (
      (arg === "chain" || arg === "/wallet") &&
      (args[i + 1] === "solana" || args[i + 1] === "base")
    ) {
      result.chain = args[i + 1] as "solana" | "base";
      i++;
    } else if (arg === "login") {
      result.login = true;
      // `login brk_…` is the non-interactive form; bare `login` prompts.
      if (args[i + 1] && !args[i + 1].startsWith("-")) {
        result.loginKey = args[i + 1];
        i++;
      }
    } else if (arg === "logout") {
      result.logout = true;
    } else if (arg === "policy") {
      // Everything after `policy` belongs to the policy command.
      result.policy = true;
      result.policyArgs = args.slice(i + 1);
      break;
    } else if (arg === "--port" && args[i + 1]) {
      result.port = parseInt(args[i + 1], 10);
      i++;
    } else if (arg === "--no-reuse") {
      result.noReuse = true;
    } else if (arg === "setup") {
      result.setup = true;
    } else if (arg === "phone") {
      result.phone = true;
      const next = args[i + 1];
      if (next === "numbers") {
        result.phoneSubcommand = "numbers";
        const action = args[i + 2];
        if (action === "list" || action === "buy" || action === "renew" || action === "release") {
          result.phoneNumbersAction = action;
          i += 2;
          // Capture positional arg for buy/renew/release
          const positional = args[i + 1];
          if (positional && !positional.startsWith("--")) {
            result.phoneArg = positional;
            i++;
          }
          // Optional --area-code flag (buy only)
          while (i + 1 < args.length) {
            const flag = args[i + 1];
            if (flag === "--area-code" && args[i + 2]) {
              result.phoneAreaCode = args[i + 2];
              i += 2;
            } else if (flag.startsWith("--area-code=")) {
              result.phoneAreaCode = flag.slice("--area-code=".length);
              i++;
            } else break;
          }
        } else {
          i++;
        }
      } else if (next === "lookup" || next === "fraud") {
        result.phoneSubcommand = next;
        i++;
        const positional = args[i + 1];
        if (positional && !positional.startsWith("--")) {
          result.phoneArg = positional;
          i++;
        }
      }
    } else if (arg === "share") {
      result.share = true;
      // Next positional arg is target: "last" | "list" | resp_<id>
      const next = args[i + 1];
      if (next && !next.startsWith("--")) {
        result.shareTarget = next;
        i++;
      }
      // Scan remaining args for share-specific flags
      while (i + 1 < args.length) {
        const flag = args[i + 1];
        if (flag === "--all") {
          result.shareAll = true;
          i++;
        } else if (flag === "--as" && args[i + 2]) {
          result.sharePreset = args[i + 2];
          i += 2;
        } else if (flag.startsWith("--as=")) {
          result.sharePreset = flag.slice("--as=".length);
          i++;
        } else if (flag === "--limit" && args[i + 2]) {
          result.shareLimit = Math.min(Math.max(parseInt(args[i + 2], 10) || 20, 1), 100);
          i += 2;
        } else if (flag.startsWith("--limit=")) {
          result.shareLimit = Math.min(
            Math.max(parseInt(flag.slice("--limit=".length), 10) || 20, 1),
            100,
          );
          i++;
        } else {
          break;
        }
      }
    }
  }

  return result;
}

/**
 * Read a key from the terminal for a bare `clawrouter login`.
 *
 * Echoed, not hidden. A hidden prompt would be nicer, but the common failure
 * here is a mis-paste, and a key the user cannot see is a key they cannot
 * check — the token is about to be written to a file on this machine anyway.
 */
async function promptForApiKey(): Promise<string> {
  const { createInterface } = await import("node:readline/promises");
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    console.log(`Sign up, add credit with a card, and mint a key at ${PORTAL_KEYS_URL}`);
    return (await rl.question("Paste your BlockRun API key (brk_...): ")).trim();
  } finally {
    rl.close();
  }
}

/** SIGINT/SIGTERM → close the proxy, then exit. Shared by both auth modes. */
function installShutdownHandlers(proxy: { close: () => Promise<void> }): void {
  const shutdown = async (signal: string) => {
    console.log(`\n[ClawRouter] Received ${signal}, shutting down...`);
    try {
      await proxy.close();
      console.log(`[ClawRouter] Proxy closed`);
      process.exit(0);
    } catch (err) {
      console.error(`[ClawRouter] Error during shutdown: ${err}`);
      process.exit(1);
    }
  };
  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));
}

/**
 * Start the proxy against api.blockrun.ai with a customer API key.
 *
 * Deliberately a separate path from the wallet start rather than a set of
 * `if (apiKey)` branches inside it: almost none of the wallet startup applies.
 * There is no chain to report, no address to print, no local balance to read
 * and no funding instruction to give — the answer to "am I out of money" comes
 * from the gateway as a 402, and the answer to "where do I add some" is a URL,
 * not an address.
 */
async function startWithApiKey(
  apiKey: string,
  source: string,
  args: ReturnType<typeof parseArgs>,
): Promise<void> {
  const origin =
    source === "env" ? "BLOCKRUN_API_KEY" : source === "core" ? "~/.blockrun/.api-key" : source;
  console.log(`[ClawRouter] Using BlockRun API key ${maskApiKey(apiKey)} (from ${origin})`);

  const proxy = await startProxy({
    apiKey,
    port: args.port,
    allowExistingProxy: !args.noReuse,
    onReady: (port) => {
      console.log(`[ClawRouter] v${VERSION} | Proxy listening on http://127.0.0.1:${port}`);
      console.log(`[ClawRouter] Health check: http://127.0.0.1:${port}/health`);
    },
    onError: (error) => {
      console.error(`[ClawRouter] Error: ${error.message}`);
    },
    onRouted: (decision) => {
      const cost = decision.costEstimate.toFixed(4);
      const saved = (decision.savings * 100).toFixed(0);
      console.log(`[ClawRouter] [${decision.tier}] ${decision.model} $${cost} (saved ${saved}%)`);
    },
  });

  console.log(`[ClawRouter] Billing: BlockRun account credit — ${PORTAL_CREDITS_URL}`);
  console.log(`[ClawRouter] Ready - Ctrl+C to stop`);

  installShutdownHandlers(proxy);
  await new Promise(() => {});
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  if (args.version) {
    console.log(VERSION);
    process.exit(0);
  }

  if (args.help) {
    printHelp();
    process.exit(0);
  }

  if (args.setup) {
    await cmdSetup();
    process.exit(0);
  }

  // Local file operation — no running proxy needed. Non-zero exit on any rejection.
  if (args.policy) {
    const result = runPolicyCommand(args.policyArgs);
    if (result.isError) {
      console.error(`✗ ${result.text}`);
      process.exit(1);
    }
    console.log(result.text);
    process.exit(0);
  }

  // Query commands — talk to running proxy
  const queryPort = args.port ?? getProxyPort();

  if (args.queryStatus) {
    await cmdStatus(queryPort);
    process.exit(0);
  }
  if (args.queryWallet) {
    await cmdWallet(queryPort);
    process.exit(0);
  }
  if (args.queryModels) {
    await cmdModels(queryPort);
    process.exit(0);
  }
  if (args.queryStats) {
    await cmdStats(queryPort, args.queryStatsDays);
    process.exit(0);
  }
  if (args.reconcile) {
    await cmdReconcile(args.reconcileDays);
    process.exit(0);
  }

  if (args.queryCache) {
    await cmdCache(queryPort);
    process.exit(0);
  }

  if (args.share) {
    await cmdShare(queryPort, args.shareTarget, args.sharePreset, args.shareLimit, args.shareAll);
    process.exit(0);
  }

  if (args.phone) {
    if (!args.phoneSubcommand) {
      console.error("✗ Usage: clawrouter phone <numbers|lookup|fraud> ...");
      console.error("  See: clawrouter --help");
      process.exit(1);
    }
    await cmdPhone(
      queryPort,
      args.phoneSubcommand,
      args.phoneNumbersAction,
      args.phoneArg,
      args.phoneAreaCode,
    );
    process.exit(0);
  }

  if (args.doctor) {
    // Parse: doctor [opus|sonnet] [question...]
    const rawArgs = process.argv.slice(2);
    const doctorIndex = rawArgs.findIndex((a) => a === "doctor" || a === "--doctor");
    const afterDoctor = rawArgs.slice(doctorIndex + 1);

    // Check if first arg is model selection
    let model: "sonnet" | "opus" = "sonnet"; // default to cheaper
    let questionArgs = afterDoctor;

    if (afterDoctor[0] === "opus") {
      model = "opus";
      questionArgs = afterDoctor.slice(1);
    } else if (afterDoctor[0] === "sonnet") {
      model = "sonnet";
      questionArgs = afterDoctor.slice(1);
    }

    const userQuestion = questionArgs.join(" ").trim() || undefined;
    await runDoctor(userQuestion, model);
    process.exit(0);
  }

  if (args.logs) {
    const output = await formatRecentLogs(args.logsDays);
    console.log(output);
    process.exit(0);
  }

  if (args.partners) {
    if (PARTNER_SERVICES.length === 0) {
      console.log("No partner APIs available.");
      process.exit(0);
    }

    console.log(`\nClawRouter Partner APIs (v${VERSION})\n`);

    // Compact grouped view — one line per tool, grouped by category.
    const byCategory = new Map<string, typeof PARTNER_SERVICES>();
    for (const svc of PARTNER_SERVICES) {
      const bucket = byCategory.get(svc.category) ?? [];
      bucket.push(svc);
      byCategory.set(svc.category, bucket);
    }
    const toolWidth = Math.max(...PARTNER_SERVICES.map((s) => `blockrun_${s.id}`.length), 28);
    const priceWidth = Math.max(
      ...PARTNER_SERVICES.map((s) =>
        s.pricing.perUnit === "free" ? 4 : `${s.pricing.perUnit}/${s.pricing.unit}`.length,
      ),
      12,
    );
    for (const [category, services] of byCategory) {
      console.log(`${category}`);
      for (const svc of services) {
        const tool = `blockrun_${svc.id}`.padEnd(toolWidth);
        const price = (
          svc.pricing.perUnit === "free" ? "free" : `${svc.pricing.perUnit}/${svc.pricing.unit}`
        ).padEnd(priceWidth);
        console.log(`  ${tool}  ${price}  ${svc.shortDescription}`);
      }
      console.log();
    }

    if (args.partnersTest) {
      console.log("Testing partner endpoints...\n");
      const apiBase = "https://blockrun.ai/api";
      for (const svc of PARTNER_SERVICES) {
        const url = `${apiBase}/v1${svc.proxyPath}`;
        try {
          const response = await fetch(url, { method: "GET" });
          const status = response.status;
          const ok = status === 402 ? "alive (402 = payment required)" : `status ${status}`;
          console.log(`  ${svc.id}: ${ok}`);
        } catch (err) {
          console.log(`  ${svc.id}: error - ${err instanceof Error ? err.message : String(err)}`);
        }
      }
      console.log();
    }

    process.exit(0);
  }

  if (args.walletRecover) {
    await recoverWalletFromMnemonic();
    process.exit(0);
  }

  if (args.login) {
    const key = args.loginKey ?? (await promptForApiKey());
    if (!isValidApiKey(key)) {
      console.error(`[ClawRouter] That does not look like a BlockRun API key (expected brk_...).`);
      console.error(`[ClawRouter] Sign up and mint one at ${PORTAL_KEYS_URL}`);
      process.exit(1);
    }
    const path = await saveApiKey(key);
    console.log(`[ClawRouter] Signed in with ${maskApiKey(key)}`);
    console.log(`[ClawRouter] Key saved to ${path} (readable only by you)`);
    console.log(`[ClawRouter] Calls now go to api.blockrun.ai and bill your account credit.`);
    console.log(`[ClawRouter] Top up: ${PORTAL_CREDITS_URL}`);
    console.log(`[ClawRouter] Restart the proxy to apply.`);
    process.exit(0);
  }

  if (args.logout) {
    const { removed, envStillSet } = await clearApiKey();
    if (removed.length === 0) {
      console.log(`[ClawRouter] No stored API key — already using the wallet.`);
    } else {
      for (const path of removed) console.log(`[ClawRouter] Removed ${path}`);
      console.log(`[ClawRouter] Back to wallet mode (x402). Restart the proxy to apply.`);
    }
    if (envStillSet) {
      console.warn(
        `[ClawRouter] ⚠ BLOCKRUN_API_KEY is still set in this environment and overrides the wallet.`,
      );
      console.warn(`[ClawRouter]   Unset it too: unset BLOCKRUN_API_KEY`);
    }
    process.exit(0);
  }

  if (args.chain) {
    const targetChain = args.chain;

    if (targetChain === "solana") {
      // Reuse the BlockRun Core Solana wallet, migrating a legacy mnemonic on
      // first use. Only generate a new Solana key if neither source exists.
      const { MNEMONIC_FILE, setupSolana } = await import("./auth.js");
      const { getSolanaAddress } = await import("./wallet.js");
      const wallet = await resolveOrGenerateWalletKey();

      let solanaAddr: string;
      if (wallet.solanaPrivateKeyBytes) {
        solanaAddr = await getSolanaAddress(wallet.solanaPrivateKeyBytes);
        console.log(`[ClawRouter] Using BlockRun Core Solana wallet.`);
      } else {
        // First time — generate a Core Solana key and keep a recovery mnemonic.
        console.log(`[ClawRouter] Setting up Solana wallet...`);
        const { solanaPrivateKeyBytes } = await setupSolana();
        solanaAddr = await getSolanaAddress(solanaPrivateKeyBytes);
        console.log(`[ClawRouter] Solana wallet created.`);
        console.log(`[ClawRouter] ⚠  Back up your mnemonic: ${MNEMONIC_FILE}`);
      }

      await savePaymentChain("solana");
      console.log(`[ClawRouter] Payment chain → Solana`);
      console.log(`[ClawRouter] Solana address : ${solanaAddr}`);
      console.log(`[ClawRouter] Fund USDC at   : https://solscan.io/account/${solanaAddr}`);
    } else {
      await savePaymentChain("base");
      console.log(`[ClawRouter] Payment chain → Base (EVM)`);
    }

    console.log(
      `[ClawRouter] Restart gateway to apply: systemctl --user restart openclaw-gateway.service`,
    );
    console.log(`[ClawRouter]   or: openclaw gateway restart`);
    process.exit(0);
  }

  if (args.report) {
    const report = await generateReport(args.reportPeriod, args.reportJson);
    console.log(report);
    process.exit(0);
  }

  // Credential resolution. The API key is checked FIRST and, when present,
  // no wallet is resolved at all — resolveOrGenerateWalletKey() *generates* a
  // wallet as a side effect, and a card-paying user should never find a
  // freshly minted private key and a "back this up now" banner they have no
  // use for.
  const apiKeyResolution = await resolveApiKey();
  if (apiKeyResolution) {
    await startWithApiKey(apiKeyResolution.key, apiKeyResolution.source, args);
    return;
  }

  // Resolve wallet key
  const wallet = await resolveOrGenerateWalletKey();

  if (wallet.source === "generated") {
    console.log(`[ClawRouter] Generated new wallet: ${wallet.address}`);
  } else if (wallet.source === "core") {
    console.log(`[ClawRouter] Using BlockRun Core wallet: ${wallet.address}`);
  } else if (wallet.source === "saved") {
    console.log(`[ClawRouter] Using saved wallet: ${wallet.address}`);
  } else if (wallet.source === "config") {
    console.log(`[ClawRouter] Using wallet from plugin config: ${wallet.address}`);
  } else {
    console.log(`[ClawRouter] Using wallet from BLOCKRUN_WALLET_KEY: ${wallet.address}`);
  }

  // Show Solana address if available
  if (wallet.solanaPrivateKeyBytes) {
    try {
      const solAddr = await getSolanaAddress(wallet.solanaPrivateKeyBytes);
      console.log(`[ClawRouter] Solana address: ${solAddr}`);
    } catch {
      // Non-fatal
    }
  }

  // Start the proxy
  const proxy = await startProxy({
    wallet,
    port: args.port,
    allowExistingProxy: !args.noReuse,
    onReady: (port) => {
      console.log(`[ClawRouter] v${VERSION} | Proxy listening on http://127.0.0.1:${port}`);
      console.log(`[ClawRouter] Health check: http://127.0.0.1:${port}/health`);
    },
    onError: (error) => {
      console.error(`[ClawRouter] Error: ${error.message}`);
    },
    onRouted: (decision) => {
      const cost = decision.costEstimate.toFixed(4);
      const saved = (decision.savings * 100).toFixed(0);
      console.log(`[ClawRouter] [${decision.tier}] ${decision.model} $${cost} (saved ${saved}%)`);
    },
    onLowBalance: (info) => {
      console.warn(`[ClawRouter] Low balance: ${info.balanceUSD}. Fund: ${info.walletAddress}`);
    },
    onInsufficientFunds: (info) => {
      console.error(
        `[ClawRouter] Insufficient funds. Balance: ${info.balanceUSD}, Need: ${info.requiredUSD}`,
      );
      console.error(`[ClawRouter] Need help? Run: npx @blockrun/clawrouter doctor`);
    },
  });

  // Check balance on the active payment chain
  const paymentChain = await resolvePaymentChain();
  const displayAddress =
    paymentChain === "solana" && proxy.solanaAddress ? proxy.solanaAddress : wallet.address;
  try {
    const balance = await proxy.balanceMonitor.checkBalance();
    if (balance.isEmpty) {
      console.log(`[ClawRouter] Wallet balance: $0.00 (using FREE model)`);
      console.log(`[ClawRouter] Fund wallet for premium models: ${displayAddress}`);
    } else if (balance.isLow) {
      console.log(`[ClawRouter] Wallet balance: ${balance.balanceUSD} (low)`);
    } else {
      console.log(`[ClawRouter] Wallet balance: ${balance.balanceUSD}`);
    }
    // Invalidate after display so the first real request always gets a fresh check.
    // Prevents a flaky RPC at startup from caching a false $0.00 and triggering
    // free-model fallback on the first request.
    proxy.balanceMonitor.invalidate();
  } catch {
    console.log(`[ClawRouter] Wallet: ${displayAddress} (balance check pending)`);
  }

  console.log(`[ClawRouter] Ready - Ctrl+C to stop`);

  // Handle graceful shutdown
  installShutdownHandlers(proxy);

  // Keep process alive
  await new Promise(() => {});
}

main().catch((err) => {
  console.error(`[ClawRouter] Fatal error: ${err.message}`);
  console.error(`[ClawRouter] Need help? Run: npx @blockrun/clawrouter doctor`);
  process.exit(1);
});
